### ISSUE TITLE
Peer to peer code review - Note

### ISSUE THREAD

**Issue by Xecyc** [IsmaelMastronardi/Portfolio#3]
the background image in the mobile version is not showing up.

![image](https://github.com/IsmaelMastronardi/Portfolio/assets/47494310/fef57126-a2a8-418e-b930-f58ebc2e4c87)

To solve this you can add two dots to the root location of the image, like this:

![image](https://github.com/IsmaelMastronardi/Portfolio/assets/47494310/1b509873-86e4-471e-98fb-11e90b927436)

**Comment by IsmaelMastronardi** [comment]
Issue fixed. Thank you for the comment.
